name: Build & Push Docker Image

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      content: read 
      packages: write 

    steps:
      - name: Checkout repository
        uses: action/checkout@v4

      - name: Log in to GitHub Container Registry 
        uses: docker/login-action@v3
        with:
          registry: ghcr.io 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch name 
        id: vars 
        run: echo "BRANCH_NAME=${GITHUB_REF_NAME}" >> $GITHUB_ENV 

      - name: Build & Push Docker image 
        uses: docker/build-push-action@v6
        with:
          context: . 
          push: true 
          tags: ghcr.io/${{ github.repository }}:${{ env.BRANCH_NAME }}

